llama:
  params:
     top_k : 30
     max_new_tokens : 500
     num_return_sequences: 1
    
  templates:
    crawl_company_info: |

    crawl_product_info: |    

    crawl_company_info_default: |

    crawl_product_info_default: |

    crawl_default_prompt: |
      
    system_default: |
                    You must distinguish among South Korea's mobile telecommunication companies (skt, kt, lg u+).

                    Provide answers with ONLY 'yes' or 'no'. no more answer

chatgpt:
  params:
    model: gpt-3.5-turbo #gpt-4
    
  templates:
    prompt_template: |
                     내용 : {page_content}, 날짜 : {날짜}
                        
    answer_prompt: |
                   Given the following conversation and a follow up Input, rephrase the follow up Input to be a standalone Input, in its original language.
    
    answer_default: |
                    Chat History:{chat_history}ß
                    Follow Up Input:{question}
                    Standalone question:

    report_default: |
                    Here is a list about data our company {context}

    report_default_prompt: |
                           Develop a analysis report about our cafe, Structure of report is follwing format
                           Executive Summary: Provide a concise overview of the report's findings and recommendations.  
                           Study Introduction: Introduce the company and its background, including its mission, vision, and core values.
                           Methodology: Explain the research methods, data sources, and analytical tools used.
                           Review of Statistics: Give a detailed analysis of each component, including market analysis, SWOT analysis, financial analysis, etc.
                           Conclusion: Give a summary of the main findings and insights derived from the analysis
                           References: Citations of the sources used in the report, ensuring credibility and transparency


embedding:
  params: None
  


  
  